[![Open In Colab](https://colab.research.google.com/assets/colab-badge.svg)](https://colab.research.google.com/github/LeoLin72/IULM_DDM2324_Notebooks/blob/main/03_introduzione_a_numpy.ipynb)

# Introduzione a Numpy
numpy è una delle librerie più fondamentali per la computazione scientifica in Python. Offre supporto per array (inclusi array multidimensionali), oltre a una vasta gamma di funzioni matematiche per operare su questi array. Con numpy, diventa facile e veloce effettuare operazioni come addizioni, moltiplicazioni e trasformazioni su grandi quantità di dati.

##Installazione e Importazione
Prima di utilizzare numpy, è necessario installarlo:

In [1]:
!pip install numpy

Una volta installato, puoi importarlo nel tuo script o notebook:

In [2]:
import numpy as np

Qui, np è un alias comune utilizzato per numpy.

## Creazione di Array
Un array è una collezione di elementi, tutti dello stesso tipo, indicizzati da una tupla di interi non negativi. Ecco come puoi creare array usando numpy:

In [3]:
# Array monodimensionale
array_1d = np.array([1, 2, 3, 4])
print(array_1d)

# Array bidimensionale (matrice)
array_2d = np.array([[1, 2], [3, 4], [5, 6]])
print(array_2d)

[1 2 3 4]
[[1 2]
 [3 4]
 [5 6]]


## Operazioni Matematiche
Con numpy, puoi eseguire operazioni elemento per elemento sugli array, come addizione, sottrazione, moltiplicazione e divisione:

In [4]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

somma = a + b
print("Somma:", somma)

prodotto = a * b
print("Prodotto:", prodotto)


Somma: [5 7 9]
Prodotto: [ 4 10 18]


## Funzioni Utili
numpy offre molte funzioni utili per operazioni matematiche, statistiche e di trasformazione. Alcuni esempi:

In [5]:
array = np.array([1, 2, 3, 4, 5])

# Media
print("Media:", np.mean(array))

# Mediana
print("Mediana:", np.median(array))

# Riformattazione
matrice = array.reshape(5, 1)
print("Matrice riformattata:\n", matrice)


Media: 3.0
Mediana: 3.0
Matrice riformattata:
 [[1]
 [2]
 [3]
 [4]
 [5]]


## Tipi di Dato in Numpy


In [6]:
# Creazione di un array di interi
a = np.array([1, 2, 3], dtype='int32')
print(a)

# Creazione di un array di float
b = np.array([1.5, 2.5, 3.5], dtype='float64')
print(b)

# Creazione di un array di booleani
c = np.array([True, False, True], dtype='bool')
print(c)

[1 2 3]
[1.5 2.5 3.5]
[ True False  True]


È importante notare che, mentre in Python standard la dimensione dei tipi int e float può variare a seconda della piattaforma, in numpy la dimensione dei tipi è sempre fissa, indipendentemente dalla piattaforma. Questo garantisce che i dati siano rappresentati in modo uniforme attraverso diverse piattaforme, rendendo numpy ideale per la computazione scientifica e la manipolazione di dati.

## Accesso ai Dati e Relazione tra Numpy e Liste Python
In numpy, l'accesso ai dati negli array avviene tramite indici, proprio come nelle liste Python. Tuttavia, gli array di numpy forniscono molta più flessibilità rispetto alle liste native, in particolare quando si tratta di array multidimensionali.

### Accesso ai Dati tramite Indici in Numpy:

Un array unidimensionale si comporta in modo molto simile a una lista standard:

In [7]:
arr = np.array([1, 2, 3, 4, 5])
print(arr[0])   # Stampa "1"
print(arr[-1])  # Stampa "5", gli indici negativi partono dall'ultimo elemento a ritroso

1
5


Ma la vera potenza di numpy emerge quando si lavora con array multidimensionali:

In [8]:
matrix = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(matrix[1, 2])  # Stampa "6" (seconda riga, terza colonna)


6


Inoltre, numpy offre potenti funzionalità di slicing che permettono di accedere a sottosezioni dell'array:

In [9]:
print(matrix[1, :])  # Stampa "[4 5 6]", ovvero la seconda riga completa


[4 5 6]


## Numpy vs Liste Python

Sebbene gli array di numpy possano sembrare simili alle liste Python in superficie, ci sono alcune differenze chiave:

- **Omotipia**: Mentre una lista Python può contenere oggetti di tipo misto, un array numpy è omogeneo; tutti gli elementi devono essere dello stesso tipo.
- **Efficienza**: Gli array di numpy sono più efficienti dal punto di vista della memoria e offrono prestazioni migliori per operazioni numeriche rispetto alle liste Python.
- **Funzionalità**: numpy fornisce una vasta gamma di funzioni matematiche e statistiche che possono essere eseguite direttamente sugli array.
- **Dimensionalità**: Mentre una lista Python è essenzialmente un array unidimensionale, numpy può gestire array multidimensionali. Questo lo rende particolarmente utile per operazioni come la manipolazione di matrici.

In sintesi, mentre le liste Python sono utili per una vasta gamma di compiti generali, gli array di numpy sono ottimizzati per operazioni numeriche e matriciali ad alte prestazioni.

## Accesso alla Forma dell'Array con shape
La proprietà 'shape' di un array numpy fornisce una tupla che rappresenta la dimensione di ciascun asse dell'array. È uno degli attributi più utili perché permette di comprendere immediatamente la "forma" dell'array, cioè quante righe, colonne o altre dimensioni contiene.

### Esempio con un Array Unidimensionale

In [10]:
arr = np.array([1, 2, 3, 4, 5])
print(arr.shape)  # Stampa "(5,)", indicando che l'array ha 5 elementi lungo il suo unico asse.

(5,)


### Esempio con un Array Bidimensionale (Matrice)

In [14]:
matrix = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(matrix.shape)  # Stampa "(3, 3)", indicando che la matrice ha 3 righe e 3 colonne.


(3, 3)


La proprietà shape è particolarmente utile quando si lavora con dataset di grandi dimensioni o con array di forme complesse, poiché fornisce una chiara indicazione di come sono strutturati i dati.